### PR TITLE
Addresses off by one error in map display

### PR DESCRIPTION
**Pull request by JPrevost**
See #107

This really is a hack, but it’s simple and likely safe. Maybe.

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
I'm not ignoring this PR, btw - the problem that occurs shows its face only in rare conditions, and I haven't been able to isolate such a case. Once I do, I'll be able to check whether this solves the issue.

**Comment by JPrevost** [comment]
This may be a current test case:
http://oastats.mit.edu/public.php?filter%5B%5D=AgeLab#tabs=2

**Comment by matt-bernhardt** [comment]
:+1: This looks like it'll work - go ahead and merge, and I'll deploy to dev.

**Comment by JPrevost** [comment]
Cool. I'm going to rebase so the tree is sane then I'll merge it.

**Comment by JPrevost** [comment]
closes #107

**Pull request merged**
